import { ArrowDownLeft, ArrowUpRight, CheckCircle2, Clock3, History } from "lucide-react";
import { getServerSession } from "next-auth";
import prisma from "@repo/db/client";
import { authOptions } from "../../lib/auth";

export const metadata = { title: "Transactions | Paywall", description: "Your complete Paywall activity" };

export default async function TransactionsPage() {
  const session = await getServerSession(authOptions);
  const userId = Number(session?.user?.id);
  const [sent, received, topups] = await Promise.all([
    prisma.p2pTransfer.findMany({ where: { fromUserId: userId }, orderBy: { timestamp: "desc" }, take: 50, include: { toUser: { select: { name: true, number: true } } } }),
    prisma.p2pTransfer.findMany({ where: { toUserId: userId }, orderBy: { timestamp: "desc" }, take: 50, include: { fromUser: { select: { name: true, number: true } } } }),
    prisma.onRampTransaction.findMany({ where: { userId }, orderBy: { startTime: "desc" }, take: 50 }),
  ]);
  const activities = [...sent.map((item) => ({ id: `sent-${item.id}`, time: item.timestamp, amount: item.amount, direction: "out" as const, title: `Sent to ${item.toUser.name || item.toUser.number}`, status: "Completed" })), ...received.map((item) => ({ id: `received-${item.id}`, time: item.timestamp, amount: item.amount, direction: "in" as const, title: `Received from ${item.fromUser.name || item.fromUser.number}`, status: "Completed" })), ...topups.map((item) => ({ id: `topup-${item.id}`, time: item.startTime, amount: item.amount, direction: "in" as const, title: `${item.provider} top-up`, status: item.status }))].sort((a, b) => b.time.getTime() - a.time.getTime());
  return <div className="mx-auto max-w-[1120px]"><div className="mb-9 flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#6b8d53]">Activity</p><h1 className="mt-3 text-4xl font-black tracking-[-.06em]">Transactions</h1><p className="mt-2 text-sm text-[#687064]">Every top-up and transfer, in one timeline.</p></div><span className="hidden h-10 w-10 place-items-center rounded-full bg-[#e7f5dc] text-[#4a8630] sm:grid"><History className="h-4 w-4" /></span></div><section className="mb-8 grid gap-3 sm:grid-cols-3"><Metric label="Sent" value={String(sent.length)} icon={<ArrowUpRight className="h-4 w-4" />} /><Metric label="Received" value={String(received.length)} icon={<ArrowDownLeft className="h-4 w-4" />} /><Metric label="Top-ups" value={String(topups.length)} icon={<History className="h-4 w-4" />} /></section><section className="overflow-hidden rounded-2xl border border-[#e1e5dc] bg-white"><div className="flex items-center justify-between border-b border-[#e1e5dc] px-5 py-4 sm:px-6"><h2 className="text-base font-black">All activity</h2><span className="text-xs text-[#7b8577]">{activities.length} records</span></div>{!activities.length ? <div className="px-6 py-16 text-center"><p className="text-sm font-bold">No transactions yet</p><p className="mt-1 text-xs text-[#7b8577]">Your activity will appear after your first top-up or transfer.</p></div> : <div className="divide-y divide-[#edf0eb]">{activities.map((activity) => <div key={activity.id} className="flex items-center justify-between gap-4 px-5 py-4 sm:px-6"><div className="flex min-w-0 items-center gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${activity.direction === "in" ? "bg-[#e7f5dc] text-[#4a8630]" : "bg-[#fff0ef] text-[#b85b55]"}`}>{activity.direction === "in" ? <ArrowDownLeft className="h-4 w-4" /> : <ArrowUpRight className="h-4 w-4" />}</span><div className="min-w-0"><p className="truncate text-sm font-bold">{activity.title}</p><p className="mt-1 text-xs text-[#7b8577]">{activity.time.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</p></div></div><div className="text-right"><p className={`text-sm font-black ${activity.direction === "in" ? "text-[#4a8630]" : "text-[#b85b55]"}`}>{activity.direction === "in" ? "+" : "−"}₹{(activity.amount / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}</p><p className="mt-1 inline-flex items-center gap-1 text-[11px] text-[#4a8630]">{activity.status === "Pending" ? <Clock3 className="h-3 w-3 text-[#a5772e]" /> : <CheckCircle2 className="h-3 w-3" />}{activity.status}</p></div></div>)}</div>}</section></div>;
}

function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-[#e1e5dc] bg-white p-5"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#e7f5dc] text-[#4a8630]">{icon}</span><p className="mt-4 text-2xl font-black">{value}</p><p className="text-xs text-[#7b8577]">{label}</p></div>; }
