import { CheckCircle2, Clock3, CreditCard, XCircle } from "lucide-react";
import db from "@repo/db/client";
import { getCurrentMerchant } from "../../../lib/merchant";
import { ResourcePage } from "../components/ResourcePage";

export default async function PaymentsPage() {
  const merchant = await getCurrentMerchant();
  const payments = merchant ? await db.merchantPayment.findMany({ where: { merchantId: merchant.id }, orderBy: { createdAt: "desc" }, take: 100, include: { paymentLink: { select: { title: true } }, customer: { select: { name: true, email: true } } } }) : [];
  return <ResourcePage eyebrow="Activity" title="Payments" description="Review every payment event and quickly understand what needs attention.">{!payments.length ? <EmptyPayments /> : <div className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-white/[.03]"><div className="divide-y divide-white/[.07]">{payments.map((payment) => <div key={payment.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-cyan-300/10 text-cyan-200">{payment.status === "Completed" ? <CheckCircle2 className="h-4 w-4" /> : payment.status === "Failed" ? <XCircle className="h-4 w-4" /> : <Clock3 className="h-4 w-4" />}</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-white">{payment.customer?.name || "Guest checkout"}</p><p className="mt-1 truncate text-xs text-slate-500">{payment.paymentLink?.title || "Payment"} · {payment.createdAt.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</p></div></div><div className="flex items-center gap-4 sm:justify-end"><span className={`text-xs font-semibold ${payment.status === "Completed" ? "text-emerald-300" : payment.status === "Failed" ? "text-rose-300" : "text-amber-300"}`}>{payment.status}</span><p className="text-sm font-semibold text-white">₹{(payment.amount / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}</p></div></div>)}</div></div>}</ResourcePage>;
}

function EmptyPayments() { return <div className="mt-6 rounded-2xl border border-dashed border-white/15 bg-white/[0.025] px-6 py-14 text-center"><div className="mx-auto flex h-11 w-11 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-200"><CreditCard className="h-5 w-5" /></div><h2 className="mt-4 text-base font-semibold text-white">No payments yet</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">Completed checkouts will appear here with their customer and link context.</p></div>; }
