import Link from "next/link";
import { ArrowRight, Check, ChevronDown, Globe2, LockKeyhole, Menu, MoveUpRight, ShieldCheck, Smartphone, Sparkles, WalletCards } from "lucide-react";
import { ThemeToggle } from "@repo/ui/theme-toggle";

const countries = ["Australia", "Argentina", "Austria", "Belgium", "Brazil", "Canada", "China", "Denmark", "France", "Germany", "India", "Indonesia", "Ireland", "Italy", "Japan", "Kenya", "Malaysia", "Mexico", "Netherlands", "New Zealand", "Norway", "Portugal", "Singapore", "South Africa", "Spain", "Sweden", "Switzerland", "Thailand", "United Kingdom", "United States"];

const benefits = [
  ["Save on every transfer", "Clear pricing before you confirm anything."],
  ["One simple wallet", "Top up, send, and track your money in one place."],
  ["Support when you need it", "A real activity trail makes every question easier."],
];

export function HeroSection() {
  return (
    <main className="bg-[#f7f8f4] text-[#163300]">
      <section className="overflow-hidden bg-[#9fe870]">
        <header className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-12">
          <Link href="/home" className="text-xl font-black tracking-[-0.08em] text-[#163300]">paywall<span className="text-[#5e9b40]">.</span></Link>
          <nav className="hidden items-center gap-6 text-xs font-semibold md:flex"><a href="#personal" className="hover:underline">Personal</a><a href="#business" className="hover:underline">Business</a><a href="#how-it-works" className="hover:underline">How it works</a></nav>
          <div className="flex items-center gap-2 text-xs font-semibold sm:gap-4"><span className="hidden items-center gap-1 sm:inline-flex"><Globe2 className="h-3.5 w-3.5" /> EN <ChevronDown className="h-3 w-3" /></span><a href="/contact" className="hidden sm:inline">Help</a><Link href="/auth" className="hidden sm:inline">Sign in</Link><ThemeToggle /><Link href="/auth?mode=signup" className="rounded-full bg-[#163300] px-4 py-2 text-white transition hover:bg-[#2a5417]">Sign up</Link><button type="button" className="rounded-full p-2 md:hidden" aria-label="Open menu"><Menu className="h-5 w-5" /></button></div>
        </header>
        <div className="mx-auto max-w-[1440px] px-5 pb-10 pt-16 text-center sm:px-8 sm:pb-14 sm:pt-24 lg:px-12 lg:pt-28">
          <p className="text-xs font-bold uppercase tracking-[.22em] text-[#456c2e]">A simpler way to move money</p>
          <h1 className="mx-auto mt-5 max-w-5xl text-5xl font-black uppercase leading-[.88] tracking-[-.075em] sm:text-7xl lg:text-[7.2rem]">SEND, SPEND<br />AND SAVE<br />YOUR WAY</h1>
          <p className="mx-auto mt-7 max-w-md text-sm leading-6 text-[#355422] sm:text-base">Paywall keeps your wallet clear, your transfers simple, and every rupee easy to understand.</p>
          <Link href="/auth?mode=signup" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#163300] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#2a5417]">Sign up in minutes <ArrowRight className="h-4 w-4" /></Link>
          <div className="relative mx-auto mt-14 h-[250px] max-w-5xl overflow-hidden rounded-[1.5rem] bg-[#6d9c45] sm:h-[390px] sm:rounded-[2rem] lg:h-[470px]">
            <div className="absolute -left-16 bottom-[-5rem] h-72 w-72 rounded-full bg-[#385c27] sm:h-[30rem] sm:w-[30rem]" />
            <div className="absolute right-[-4rem] top-[-5rem] h-72 w-72 rounded-full bg-[#c6f49f] opacity-80 sm:h-[32rem] sm:w-[32rem]" />
            <div className="absolute bottom-6 left-7 h-24 w-40 rotate-[-12deg] rounded-2xl border-4 border-[#d5f6b7]/70 bg-[#193b0a] shadow-2xl sm:bottom-12 sm:left-20 sm:h-40 sm:w-64"><div className="flex h-full flex-col justify-between p-3 text-left text-[9px] font-bold text-[#b2e985] sm:p-5 sm:text-xs"><span>PAYWALL</span><span>•••• 2048</span></div></div>
            <div className="absolute bottom-[-2rem] left-1/2 h-64 w-36 -translate-x-1/2 rotate-[8deg] rounded-[2rem] border-[7px] border-[#14240e] bg-[#e9eee6] p-2 shadow-2xl sm:h-[360px] sm:w-52 sm:rounded-[2.5rem] sm:border-[9px]"><div className="h-5 w-14 rounded-full bg-[#14240e]" /><div className="mt-7 rounded-xl bg-[#9fe870] p-3 text-left sm:mt-12 sm:p-4"><p className="text-[8px] font-semibold text-[#587d3c] sm:text-[10px]">Available balance</p><p className="mt-1 text-lg font-black sm:text-2xl">₹80,000</p></div><div className="mt-3 space-y-2 sm:mt-5"><div className="h-2 rounded-full bg-[#cbd2c5]" /><div className="h-2 w-4/5 rounded-full bg-[#cbd2c5]" /><div className="h-2 w-3/5 rounded-full bg-[#cbd2c5]" /></div></div>
            <div className="absolute right-8 top-10 hidden rotate-[10deg] rounded-xl bg-[#f7f8f4] p-4 text-left shadow-xl sm:right-24 sm:top-14 sm:block"><p className="text-[10px] font-semibold text-[#7a8474]">Paywall transfer</p><p className="mt-2 text-2xl font-black">₹820.51</p><p className="mt-2 text-[10px] text-[#587d3c]">Completed just now</p></div>
          </div>
        </div>
      </section>

      <section id="personal" className="mx-auto max-w-[1200px] px-5 py-20 text-center sm:px-8 lg:py-28"><h2 className="mx-auto max-w-xl text-4xl font-black uppercase leading-[.9] tracking-[-.06em] sm:text-6xl">TAKE CONTROL<br />OF YOUR MONEY</h2><div className="mt-12 grid gap-8 md:grid-cols-3">{benefits.map(([title, text], index) => <div key={title} className="flex flex-col items-center"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#a8e987] text-[#163300]">{index === 0 ? <Sparkles className="h-5 w-5" /> : index === 1 ? <WalletCards className="h-5 w-5" /> : <Smartphone className="h-5 w-5" />}</span><h3 className="mt-5 text-sm font-extrabold uppercase tracking-tight">{title}</h3><p className="mt-2 max-w-[220px] text-xs leading-5 text-[#657060]">{text}</p></div>)}</div></section>

      <section id="how-it-works" className="mx-auto grid max-w-[1200px] items-center gap-12 px-5 pb-20 sm:px-8 lg:grid-cols-2 lg:pb-28"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#6b8d53]">Make every rupee count</p><h2 className="mt-4 max-w-md text-4xl font-black uppercase leading-[.9] tracking-[-.06em] sm:text-6xl">SAVE ON YOUR TRAVELS ABROAD</h2><ul className="mt-7 space-y-5 text-sm">{["Know the total cost before you send.", "Keep your transfer history in one clear place.", "Move money to another Paywall user instantly."].map((item) => <li key={item} className="flex items-start gap-3 border-b border-[#e1e5dc] pb-4"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#5e9b40]" />{item}</li>)}</ul><Link href="/auth?mode=signup" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#9fe870] px-4 py-2.5 text-xs font-bold hover:bg-[#b8f495]">Open your wallet <ArrowRight className="h-3.5 w-3.5" /></Link></div><Illustration variant="travel" /></section>

      <section id="business" className="mx-auto grid max-w-[1200px] items-center gap-12 px-5 pb-20 sm:px-8 lg:grid-cols-2 lg:pb-28"><Illustration variant="transfer" /><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#6b8d53]">Simple and transparent</p><h2 className="mt-4 max-w-md text-4xl font-black uppercase leading-[.9] tracking-[-.06em] sm:text-6xl">MAKE YOUR TRANSFER COUNT</h2><div className="mt-7 space-y-4">{["Pay the exact amount you intend.", "See status changes without refreshing your life.", "Know where your wallet stands."].map((item) => <div key={item} className="flex items-start gap-3 text-sm"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#9fe870]" />{item}</div>)}</div></div></section>

      <section className="bg-[#9fe870] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-[1200px] items-center gap-12 lg:grid-cols-2"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#587d3c]">No surprises</p><h2 className="mt-4 max-w-md text-4xl font-black uppercase leading-[.9] tracking-[-.06em] sm:text-6xl">100% TRANSPARENT</h2><p className="mt-6 max-w-md text-sm leading-6 text-[#355422]">Paywall is a simulation, so every top-up and transfer is labelled clearly. What you see is what happened.</p><Link href="/transactions" className="mt-7 inline-flex rounded-full bg-[#163300] px-4 py-2.5 text-xs font-bold text-white">See your activity <ArrowRight className="ml-2 h-3.5 w-3.5" /></Link></div><Illustration variant="receipt" /></div></section>

      <section className="mx-auto max-w-[1200px] px-5 py-20 sm:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><h2 className="max-w-sm text-4xl font-black uppercase leading-[.9] tracking-[-.06em] sm:text-6xl">EXCELLENT EVERYWHERE</h2><p className="mt-5 max-w-xs text-sm leading-6 text-[#657060]">A wallet that feels considered on every screen, from your first sign-up to your hundredth transfer.</p><div className="mt-6 flex gap-2"><button type="button" className="grid h-9 w-9 place-items-center rounded-full bg-[#edf1eb]">←</button><button type="button" className="grid h-9 w-9 place-items-center rounded-full bg-[#9fe870]">→</button></div></div><div className="grid gap-4 sm:grid-cols-2"><blockquote className="rounded-2xl bg-[#9fe870] p-6 text-sm leading-6">“I finally know what happened to every transfer. The calm interface makes the money feel manageable.”<footer className="mt-8 text-xs font-bold">— A Paywall customer</footer></blockquote><blockquote className="rounded-2xl bg-[#163300] p-6 text-sm leading-6 text-white">“The whole point is clarity. Paywall keeps the important details visible and the rest out of the way.”<footer className="mt-8 text-xs font-bold text-[#9fe870]">— Paywall team</footer></blockquote></div></div></section>

      <section className="border-t border-[#e1e5dc] px-5 py-20 sm:px-8"><div className="mx-auto max-w-[1200px] text-center"><h2 className="mx-auto max-w-xl text-4xl font-black uppercase leading-[.9] tracking-[-.06em] sm:text-6xl">TAKE PAYWALL<br />EVERYWHERE YOU GO</h2><div className="mx-auto mt-8 grid h-28 w-28 grid-cols-5 gap-1 rounded-lg bg-[#163300] p-2">{Array.from({ length: 25 }).map((_, index) => <span key={index} className={index % 3 === 0 || index % 7 === 0 ? "bg-[#9fe870]" : "bg-[#f7f8f4]"} />)}</div><p className="mt-4 text-xs text-[#657060]">Scan to open your Paywall wallet</p></div></section>

      <section className="bg-[#eef1eb] px-5 py-14 sm:px-8"><div className="mx-auto max-w-[1200px]"><h2 className="text-xl font-extrabold">Paywall works nearly everywhere</h2><p className="mt-2 text-sm text-[#657060]">Send money to people and businesses wherever your Paywall wallet is available.</p><div className="mt-8 grid grid-cols-2 gap-x-5 gap-y-4 text-xs text-[#4d5b47] sm:grid-cols-3 md:grid-cols-5">{countries.map((country) => <a href="/auth?mode=signup" key={country} className="border-b border-[#d7ddd2] pb-2 hover:text-[#163300] hover:underline">Send money to {country}</a>)}</div></div></section>
      <footer className="bg-[#f7f8f4] px-5 py-10 text-xs text-[#657060] sm:px-8"><div className="mx-auto flex max-w-[1200px] flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><span className="text-lg font-black tracking-[-.08em] text-[#163300]">paywall.</span><span>© {new Date().getFullYear()} Paywall. A simulated wallet for learning and building.</span><span><Link href="/privacy" className="hover:underline">Privacy</Link> · <Link href="/terms" className="hover:underline">Terms</Link></span></div></footer>
    </main>
  );
}

function Illustration({ variant }: { variant: "travel" | "transfer" | "receipt" }) {
  if (variant === "travel") return <div className="relative h-[360px] overflow-hidden rounded-[2rem] bg-[#dce6d3] p-6"><div className="absolute -right-16 -top-16 h-64 w-64 rounded-full bg-[#9fe870]" /><div className="absolute bottom-[-5rem] left-[-4rem] h-64 w-64 rounded-full bg-[#789c5b]" /><div className="absolute left-1/2 top-1/2 w-[230px] -translate-x-1/2 -translate-y-1/2 rotate-[-8deg] rounded-2xl bg-[#f7f8f4] p-4 shadow-2xl"><div className="flex items-center justify-between"><span className="text-xs font-black">PAYWALL</span><span className="rounded-full bg-[#9fe870] px-2 py-1 text-[9px] font-bold">TRAVEL</span></div><div className="mt-8 flex items-center justify-between text-xs"><span>INR</span><MoveUpRight className="h-4 w-4" /><span>EUR</span></div><p className="mt-4 text-3xl font-black">₹80,000</p><div className="mt-4 h-2 rounded-full bg-[#dbe2d5]" /><div className="mt-2 h-2 w-3/4 rounded-full bg-[#dbe2d5]" /></div></div>;
  if (variant === "receipt") return <div className="relative mx-auto h-[340px] w-full max-w-[420px] rounded-[2rem] bg-[#d8f8c0] p-5"><div className="absolute right-6 top-5 rounded-full bg-[#163300] px-3 py-1 text-[10px] font-bold text-white">Completed</div><div className="absolute bottom-6 left-6 right-6 rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#9fe870]"><Check className="h-4 w-4" /></span><div><p className="text-xs font-bold">You sent exactly</p><p className="mt-1 text-2xl font-black">₹80,000.00</p></div></div><div className="mt-6 space-y-3 text-xs"><div className="flex justify-between"><span className="text-[#657060]">Recipient</span><b>Paywall wallet</b></div><div className="flex justify-between"><span className="text-[#657060]">Reference</span><b>PW-2048</b></div><div className="flex justify-between"><span className="text-[#657060]">Status</span><b className="text-[#4a8630]">Completed</b></div></div></div></div>;
  return <div className="relative h-[360px] overflow-hidden rounded-[2rem] bg-[#eef1eb] p-6"><div className="absolute left-8 top-8 grid h-14 w-14 place-items-center rounded-full bg-[#9fe870]"><ShieldCheck className="h-6 w-6" /></div><div className="absolute right-8 top-20 grid h-14 w-14 place-items-center rounded-full bg-[#163300] text-white"><LockKeyhole className="h-6 w-6" /></div><div className="absolute bottom-10 left-1/2 w-56 -translate-x-1/2 rounded-2xl bg-white p-5 shadow-xl"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#657060]">Transfer details</p><p className="mt-3 text-3xl font-black">₹820.51</p><div className="mt-5 flex items-center justify-between border-t border-[#e1e5dc] pt-3 text-xs"><span>To Piyush</span><span className="font-bold text-[#4a8630]">Done</span></div></div></div>;
}
