"use client";

import { useState } from "react";
import { ArrowDownLeft, ArrowUpRight, CheckCircle2, Clock3, XCircle } from "lucide-react";

type Transaction = { time: Date; amount: number; status: string; provider?: string | null };

export const OnRampTransaction = ({ transactions, title = "Recent transactions" }: { transactions: Transaction[]; title?: string }) => {
  const [showAll, setShowAll] = useState(false);
  const isSent = title.toLowerCase().includes("sent");
  const displayed = showAll ? transactions : transactions.slice(0, 5);
  return <section className="rounded-2xl border border-[#e1e5dc] bg-white p-5 sm:p-6">{title ? <div className="mb-5 flex items-center justify-between"><h2 className="text-base font-black">{title}</h2>{transactions.length > 5 ? <button type="button" onClick={() => setShowAll(!showAll)} className="text-xs font-bold text-[#4a8630] hover:underline">{showAll ? "Show less" : "View all"}</button> : null}</div> : null}{!transactions.length ? <div className="rounded-xl border border-dashed border-[#d6ddd0] px-4 py-10 text-center"><p className="text-sm font-bold">No transactions yet</p><p className="mt-1 text-xs text-[#7b8577]">Your activity will appear here after your first top-up.</p></div> : <div className="divide-y divide-[#edf0eb]">{displayed.map((transaction, index) => { const failed = transaction.status === "Failed"; const pending = transaction.status === "Pending"; const positive = !isSent; return <div key={`${transaction.time.toISOString()}-${index}`} className="flex items-center justify-between gap-4 py-4 first:pt-0 last:pb-0"><div className="flex min-w-0 items-center gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${positive ? "bg-[#e7f5dc] text-[#4a8630]" : "bg-[#fff0ef] text-[#b85b55]"}`}>{positive ? <ArrowDownLeft className="h-4 w-4" /> : <ArrowUpRight className="h-4 w-4" />}</span><div className="min-w-0"><p className="truncate text-sm font-bold">{isSent ? "Sent money" : transaction.provider || "Wallet top-up"}</p><p className="mt-0.5 text-xs text-[#7b8577]">{transaction.time.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</p></div></div><div className="text-right"><p className={`text-sm font-black ${positive ? "text-[#4a8630]" : "text-[#b85b55]"}`}>{positive ? "+" : "−"}₹{(transaction.amount / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}</p><p className={`mt-0.5 inline-flex items-center gap-1 text-[11px] ${failed ? "text-[#b85b55]" : pending ? "text-[#a5772e]" : "text-[#4a8630]"}`}>{failed ? <XCircle className="h-3 w-3" /> : pending ? <Clock3 className="h-3 w-3" /> : <CheckCircle2 className="h-3 w-3" />}{failed ? "Failed" : pending ? "Processing" : "Completed"}</p></div></div>; })}</div>}</section>;
};
